### PR TITLE
I need it for my sister.

### PR DESCRIPTION
**Pull request by amandewatnitrr**
My sister is suffering from Brain Tumour and maybe this is the last birthday of her i might be celebrating. I am far from her town and due to covid unable to travel. i just want to wish her one last time and see her happy.

I will regret if I can't gift her anything, please help me getting this game setup.

Please!!!

### CODE REVIEW

**Comment by alexeychikk** [comment]
@amandewatnitrr Ok. Just tell me what issues are you facing and I will answer you when I have free time.

**Comment by amandewatnitrr** [comment]
Thanks a lot @alexeychikk. I am facing issues with setting it up I did [npm install],[ npm start] and other stuff but didn't work also, I don't know how to deploy.

**Comment by alexeychikk** [comment]
@amandewatnitrr Please provide me with the error logs and the exact steps that you find not clear about deploy.
Also, do you have any experience in Node.js / JavaScript / Web development?

**Comment by amandewatnitrr** [comment]
E:\Website\happy-birthday-shreya\src>npm install                                                                        npm WARN EBADENGINE Unsupported engine {                                                                                npm WARN EBADENGINE   package: 'happy-birthday-orly@1.0.0',                                                             npm WARN EBADENGINE   required: { node: '10.x' },                                                                       npm WARN EBADENGINE   current: { node: 'v12.18.3', npm: '7.16.0' }                                                      npm WARN EBADENGINE }                                                                                                   npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained       npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained         npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated                                    npm WARN deprecated html-webpack-plugin@2.5.0: out of support                                                           npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated                                 npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                                                                                       npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                                                                                                npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                                                                                                npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                                                                                                npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'                                        npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.                     npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained         npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'                                                       npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.                                                                                                                                              added 1079 packages, and audited 1080 packages in 2m                                                                                                                                                                                            57 packages are looking for funding                                                                                       run `npm fund` for details                                                                                                                                                                                                                    18 vulnerabilities (6 low, 8 moderate, 2 high, 2 critical)                                                                                                                                                                                      To address issues that do not require attention, run:                                                                     npm audit fix                                                                                                                                                                                                                                 To address all issues (including breaking changes), run:                                                                  npm audit fix --force                                                                                                                                                                                                                         Run `npm audit` for details.                                                                                                                                                                                                                    E:\Website\happy-birthday-shreya\src>npm start                                                                                                                                                                                                  > happy-birthday-orly@1.0.0 start                                                                                       > webpack-dev-server --config webpack/webpack.dev.js                                                                                                                                                                                            internal/modules/cjs/loader.js:968                                                                                        throw err;                                                                                                              ^                                                                                                                                                                                                                                             Error: Cannot find module 'webpack/bin/config-optimist'                                                                 Require stack:                                                                                                          - E:\Website\happy-birthday-shreya\node_modules\webpack-dev-server\bin\webpack-dev-server.js                                at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)                                             at Function.Module._load (internal/modules/cjs/loader.js:841:27)                                                        at Module.require (internal/modules/cjs/loader.js:1025:19)                                                              at require (internal/modules/cjs/helpers.js:72:18)                                                                      at Object.<anonymous> (E:\Website\happy-birthday-shreya\node_modules\webpack-dev-server\bin\webpack-dev-server.js:64:1)                                                                                                                         at Module._compile (internal/modules/cjs/loader.js:1137:30)                                                             at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)                                               at Module.load (internal/modules/cjs/loader.js:985:32)                                                                  at Function.Module._load (internal/modules/cjs/loader.js:878:14)                                                        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {                                 code: 'MODULE_NOT_FOUND',                                                                                               requireStack: [                                                                                                           'E:\\Website\\happy-birthday-shreya\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'                    ]                                                                                                                     }         



This is the error log. No, experience with Javascript and Node.js

**Comment by alexeychikk** [comment]
@amandewatnitrr Pull from my repo. I fixed dependencies. Everything should work now.

**Comment by amandewatnitrr** [comment]
> @amandewatnitrr Pull from my repo. I fixed dependencies. Everything should work now.

Thanks a lot @alexeychikk , don't know how should i thank you.

**Comment by alexeychikk** [comment]
@amandewatnitrr Send $100 😄

**Pull request closed without merging**
